version: "3.7"

# This file is only for local use.
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ".volumes/zookeeper-data:/var/lib/zookeeper/data:rw"
      - ".volumes/zookeeper-log:/var/lib/zookeeper/log:rw"
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:6.1.0
    depends_on:
      - zookeeper
    restart: unless-stopped
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 100MB limit per message
      KAFKA_MESSAGE_MAX_BYTES: 100000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 100000000
      KAFKA_LOG_RETENTION_HOURS: 48
    ports:
      - "29092:29092"
    volumes:
      - ".volumes/kafka/data:/var/lib/kafka/data:rw"
    networks:
      - kafka_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ".volumes/kafka-ui/config.yml:/config.yml"
    depends_on:
      - kafka
    networks:
      - kafka_network

  ad-validation:
    build:
      context: .
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_network