spring:
  application:
    name: ad-material-validation

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ad-material-validation
    topics: validation_requests

notifications:
  kafka:
    topic: validation_results
server:
  port: 8090
---

spring:
  config:
    activate:
      on-profile: local
materials:
  metadata:
    base-url: http://localhost:3030/v1
rules:
  base-url: http://localhost:3030/v1